#    docker-compose -f /media/Server_Apps/Docker/DC_Omoikane.yaml up -d
#  docker-compose -f ${USERDIR}/Wow_Docker/wow.yaml up -d
# docker-compose -f /srv/DC_Omoikane.yaml up -d
# docker network create traefik_proxy
version: "3.6"
services:

####### Server Tools 

#  watchtower:
#    container_name: watchtower
#    restart: always
#    image: v2tec/watchtower
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    command: --schedule "0 0 4 * * *" --cleanup




  wow_authserver:
    image: shotendo/wow
    container_name: wow_auth
    volumes:
        - ${DOCKER}/wow/etc:/wow/etc
        - ${DOCKER}/wow/logs/auth:/Logs/Auth
        - /Drives:/Drives
        - ${DOCKER}/shared:/shared
#    network_mode: host
#    networks:
#      - default
    links:
      - wowdb
    restart: always
    command: ./wow/bin/authserver
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
     


  wow_worldserver:
    image: shotendo/wow
    container_name: wow_world
    stdin_open: true
    tty: true
    volumes:
        - ${DOCKER}/wow/etc:/wow/etc
        - ${DOCKER}/wow/logs/world:/Logs/World        
        - /Drives:/Drives
        - ${DOCKER}/wow/Data:/Data        
        - ${DOCKER}/shared:/shared
#        - ${DOCKER}/wow/TDB_full_world_335.20031_2020_03_16.sql:/wow/bin/TDB_full_world_335.20031_2020_03_16.sql
#    network_mode: host
#    networks:
#      - default
    links:
      - wowdb
    restart: always
    command: /bin/bash -c "cp /Data/TDB_full_world_335.20031_2020_03_16.sql / && ./wow/bin/worldserver"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}


##### MySQL       
  wowdb:
    image: "linuxserver/mariadb"
    container_name: "wowdb"
    hostname: wowdb
    volumes:
        - ${DOCKER}/wow/mariadb:/config

    restart: always
    networks:
      - default
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

    
 #  phpMyAdmin WebUI for Managing MariaDB 
  wowphpmyadmin:
    hostname: wowphpmyadmin
    container_name: wowphpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - wowdb:db
    ports:
      - 8681:80
    environment:
      - PMA_HOST=wowdb
#      - PMA_PORT=3307
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
#      - traefik_proxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.backend=pma"
      - "traefik.frontend.rule=Host:pma.${DOMAINNAME}"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_proxy" 
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=example.com"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
      - "traefik.frontend.auth.basic.usersFile=/shared/.htpasswd"
      - "traefik.frontend.auth.basic.removeHeader=true"
      - "traefik.frontend.entryPoints=https"




  
     

  wwww_wow:
    image: shotendo/www
    container_name: wwww_wow
#    depends_on:
#      - nginx
    volumes:
        - ${DOCKER}/www:/web
        - ${WEB}/wow:/var/www/html
        - /media:/Drives
        - ${DOCKER}/shared:/shared
    networks:
#      - traefik_proxy
      - default
    ports:
      - "9699:80"
      
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - APACHE_DOCUMENT_ROOT=/web
    labels:
      - "traefik.enable=true"
      - "traefik.backend=www_wow"
      - "traefik.frontend.rule=Host:wow.${DOMAINNAME}"  
#      - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefixStrip: /organizr"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=example.com"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"              
      - "traefik.frontend.entryPoints=https"      


  
     








################## Network ############################
networks:

  default:
    driver: bridge

#networks:
#  default:
#  traefik_proxy:
#    external: true
            
